export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const SHOW_EDIT_MODAL = "SHOW_EDIT_MODAL";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const HIDE_EDIT_MODAL = "HIDE_EDIT_MODAL";
